# Generated by Django 4.2.3 on 2023-12-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='image',
        ),
    ]
