from rest_framework.routers import DefaultRouter
from django.urls import path
from .views import *
router = DefaultRouter()

router.register('blog_posts', PostViewSet)
router.register('blog_posts', PostDetailsViewSet)

router.register('comments', CommentViewSet)
router.register('comments', CommentDetailsViewSet)

router.register('contact_us', ContactUsViewSet)
router.register('contact_us', ContactUsDetailsViewSet)

router.register('contact_email', ContactEmailViewSet)
router.register('contact_email', ContactEmailDetailsViewSet)

router.register('categories', CategoryViewSet)
router.register('categories', CategoryDetailsViewSet)

router.register('blogs', PostListView, basename="blogs")
router.register('latest', LatestPostsView, basename="latest-posts")
router.register('most_liked', MostLikedPostsView, basename="most-liked-posts")

# Define custom URLs
urlpatterns = [
    # path('blogs', BlogListView.as_view(), name='blog-list'),
    # Other custom URL patterns
]

# Include URLs generated by the router
urlpatterns += router.urls
