# Generated by Django 4.2.3 on 2023-12-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_contactemail_alter_post_reading_time'),
        ('likes', '0002_like_delete_likeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blogs.post'),
        ),
    ]
